# Site settings
title: "Alexander Reyes Online Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alexander A. Reyes"
resume_title:                   "Future Cyber Security Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "areye79@wgu.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       ""
resume_contact_address:         "Greater NYC Area"

resume_header_contact_info:     "Greater NYC Area - areye79@wgu.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>Aspiring individual who has a passion for technology focusing in the Infomation Assurance (IA), but not limited to learning on how new technologies function and work in a fast pace enterprise enviorment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:           ""
  #resume_twitter_url:          ""
  #resume_dribbble_url:         ""
  #resume_facebook_url:         ""
  resume_linkedin_url:          "https://www.linkedin.com/in/alexander-reyes-cios-csis-ciw-wss-eces-7402a1103/"
  #resume_instagram_url:        ""
  resume_website_url:           "http://reywins.github.io"
  #resume_medium_url:            ""
  resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
